all: openhttest orderedhttest

openhttest: openhttest.cpp doubleHashing.cpp
	g++ openhttest.cpp doubleHashing.cpp -o openhttest
	
orderedhttest: orderedhttest.cpp  chaining.cpp
	g++ orderedhttest.cpp  chaining.cpp -o orderedhttest
